### ISSUE TITLE
Fail to build with nginx 1.13

### ISSUE THREAD

**Issue by zloyded** [gnolizuh/BLSS#108]
have these error
`ngx_blss_module/ngx_rtmp.c:545:28: note: 'ssl' was declared here
     ngx_uint_t             ssl;
                            ^
ngx_blss_module/ngx_rtmp.c:632:27: error: 'http2' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         addr[i].opt.http2 = http2;
                           ^
ngx_blss_module/ngx_rtmp.c:548:28: note: 'http2' was declared here
     ngx_uint_t             http2;
                            ^
cc1: all warnings being treated as errors
cc -c -I/usr/include/luajit-2.0.4  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -mtune=westmere -ljemalloc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -ljemalloc -march=corei7 -mtune=corei7  -DNDK_SET_VAR -Wno-deprecated-declarations -DNDK_SET_VAR -DNDK_UPSTREAM_LIST  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ndk/objs -I objs/addon/ndk -I lua-v0.10.0/src/api -I ngx_http_upstream_check_module -I ngx_blss_module -I openssl-1.0.2k/.openssl/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http/modules/perl -I ndk/src -I ndk/src -I ndk/objs -I objs/addon/ndk -I /usr/include/luajit-2.0.4 -I ngx_brotli/deps/brotli/include -I /usr/include/libxml2 -I src/mail -I src/stream \
	-o objs/addon/ngx_blss_module/ngx_rtmp_live_module.o \
	ngx_blss_module/ngx_rtmp_live_module.c
make[1]: *** [objs/addon/ngx_blss_module/ngx_rtmp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/builds/portalserv/nginx_videoplatform/BUILD/nginx_videoplatform-1.13.12'
make: *** [build] Error 2`
with version of nginx need for?

**Comment by gnolizuh** [comment]
Can you please let me know which gcc or clang version you are using to compile?
